Add the catch method to your promise. Use error as the parameter of its callback function and log error to the console.

==============
|| Solution ||
==============

const makeServerRequest = new Promise((resolve, reject) => {
  // responseFromServer is set to false to represent an unsuccessful response from a server
  let responseFromServer = false;
  makeServerRequest.catch(error => {
      if(responseFromServer) {
    resolve("We got the data");
  } else {  
    reject("Data not received");
  }
  console.log(error);
  });
  
});

makeServerRequest.then(result => {
  console.log(result);
});